blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.post,name="blog_post"),
    path("<str:str>",views.post_details,name="blog_post_details"),
   
   
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('authentication/', include("authentication.urls")),
    path('courses/', include("profile.urls")),
    path('checkout/', include("checkout.urls")),
    path('sadakah/',include("sadakah.urls")),
    path('dashboard/', include("additional.urls")),
    path('contact/', include("contact.urls")),
    path('settings/', include("settings.urls")),
    path('blog/', include("blog.urls"))

    
]+static(settings.MEDIA_URL,                          document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

profile/models.py
from django.db import models
from django.contrib.auth.models import User
#from checkout.models import *
# Create your models here.
GENDER = (
    ("man", "man"),
    ("women", "women"),
)
LEVEL=(
    ("All Levels","All Levels"),
    ("Beginner","Beginner"),
     ("Intermediate","Intermediate"),
    ("Expert","Expert"),   
)
class Instructor(models.Model):
    name=models.CharField(max_length=100)
    title= models.CharField(max_length = 200,default="")
    gender=models.CharField(max_length = 20,choices =GENDER,default = 'man')
    instructor_resume=models.TextField()
    def __str__(self):
        return self.name
class Audience(models.Model):
    point=models.CharField(max_length=700)
    def __str__(self):
        return self.point
#class Content(models.Model):
    #title=models.CharField(max_length=100)
        
class Course(models.Model):
    title = models.CharField(max_length = 200)
    slug=models.CharField(max_length=100,default="")
    fee=models.IntegerField()
    level=models.CharField(max_length = 20,choices =LEVEL,default = 'All Levels')
    duration=models.CharField(max_length = 20,default='10h 20m')
    enroled=models.IntegerField(default=10)
    instructor = models.ManyToManyField(Instructor)
    aboutCourse=models.TextField()
    link=models.CharField(max_length = 400,default='https://us04web.zoom.us/j/79969674890?pwd=zpll6laDg59zwfwUSPbTYPZnIVfACS.1')
    audience=models.ManyToManyField(Audience)
    last_modified = models.DateTimeField(auto_now_add = True)
    img = models.ImageField(upload_to = "static/media/")
    #video=models.ManyToManyField(Video)
    #content=models.ForeignKey(Content, on_delete=models.CASCADE, blank=False, null=True)
    def __str__(self):
        return self.title

class Content(models.Model):
    title=models.CharField(max_length=100)
    course=models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    #videos=models.ManyToManyField(Video)

    def __str__(self):
        return self.title
class Video(models.Model):
    caption=models.CharField(max_length=100)
    slug=models.CharField(max_length=100,default="")
    video=models.FileField(upload_to = "video/%y")
    length=models.IntegerField()
    term=models.CharField(max_length = 20,default='3h 20m')
    content=models.ForeignKey(Content, on_delete=models.CASCADE, blank=False, null=True)
    course=models.ForeignKey(Course, on_delete=models.CASCADE, blank=False, null=True)
    def save(self, *args, **kwargs):
        if self.length >= 60:
            self.term = str(int(self.length/60))+"h "+str(int(self.length%60))+"m"
        else:
            self.term = str(self.length)+"m"
        super(Video, self).save(*args, **kwargs)
    def __str__(self):
        return str(self.caption) + " : "+ str(self.term)

class UserCourse(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=True)
    course=models.ForeignKey(Course, on_delete=models.CASCADE, blank=False, null=True)
    paid=models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    #checkout=models.ForeignKey(Checkout, on_delete=models.CASCADE, blank=False, null=True)
    def __str__(self):
        return self.user.first_name+" - " +self.course.title

templates/course_lecture/course_lecture.html
{% extends 'layout.html' %}
{% block title %}
{{video.caption}}
{% endblock %}
{% block  content %}
{% include 'course_lecture/lecture.html' %}

{% endblock  %}

templates/course_lecture/lecture.html
<head>

  <!--for boostrap icon-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<style>

</style>
</head>
<div class="container-fluid p-0 mt-4 mb-5" >
  <div class="row">
    <div class="col-sm-3 col-md-6 col-lg-3 bg-secondary text-white" style="margin: 0;padding: 0;font-size: 10px;">
          <div id="accordion">
            {% for content in course.content_set.all %}
            <div class="card">
              
                <a  data-bs-toggle="collapse" href="#id{{content.id}}" style="text-decoration:none;">
                  <div class="card-header text-dark" style="background:#eff1f6;font-size:15px;font-weight:400;">
                    {{content.title}}
                    <span class="fa fa-minus " style="float:right;padding-top:7px;"></span>
                </div>
                </a>
                
                {% for video in content.video_set.all %}
                <a href="{% url 'course_lecture' course.slug video.slug %}" style="text-decoration:none;border-bottom: 1px solid grey;">
              <div id="id{{video.content.id}}" class="collapse show text-dark" data-bs-parent="#accordion">
                <div class="card-body">  
                  <i class="bi bi-play-btn-fill" style="color:red;"></i>&ensp;                  
              {{video.caption}} 
              <span style="float:right;">{{video.length}}m <i class="bi bi-lock-fill"></i></span><br>
               </div>
              </div>
                </a>
              {% endfor %}
            </div>
            {% endfor %}
           
          </div> 
    </div>
    <div class="col-sm-9 col-md-6 col-lg-9 bg-dark text-white">
      <h5 style="text-align:center;margin-bottom:0px;padding: 10px;">{{video.caption}} <a href="{% url 'course_details' course.slug %}"><span class="fas fa-window-close" style="float:right;"></span></a></h5>
      <video class="video-fluid" width="100%" controls>
        <source src="{{video.video.url}}" type="video/mp4" />
    </video>
    </div>
  </div>
</div>