blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.post,name="blog_post"),
    path("<str:str>",views.post_details,name="blog_post_details"),
   
   
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('authentication/', include("authentication.urls")),
    path('courses/', include("profile.urls")),
    path('checkout/', include("checkout.urls")),
    path('sadakah/',include("sadakah.urls")),
    path('dashboard/', include("additional.urls")),
    path('contact/', include("contact.urls")),
    path('settings/', include("settings.urls")),
    path('blog/', include("blog.urls"))

    
]+static(settings.MEDIA_URL,                          document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

profile/models.py
from django.db import models
from django.contrib.auth.models import User
#from checkout.models import *
# Create your models here.
GENDER = (
    ("man", "man"),
    ("women", "women"),
)
LEVEL=(
    ("All Levels","All Levels"),
    ("Beginner","Beginner"),
     ("Intermediate","Intermediate"),
    ("Expert","Expert"),   
)
class Instructor(models.Model):
    name=models.CharField(max_length=100)
    title= models.CharField(max_length = 200,default="")
    gender=models.CharField(max_length = 20,choices =GENDER,default = 'man')
    instructor_resume=models.TextField()
    def __str__(self):
        return self.name
class Audience(models.Model):
    point=models.CharField(max_length=700)
    def __str__(self):
        return self.point
#class Content(models.Model):
    #title=models.CharField(max_length=100)
        
class Course(models.Model):
    title = models.CharField(max_length = 200)
    slug=models.CharField(max_length=100,default="")
    fee=models.IntegerField()
    level=models.CharField(max_length = 20,choices =LEVEL,default = 'All Levels')
    duration=models.CharField(max_length = 20,default='10h 20m')
    enroled=models.IntegerField(default=10)
    instructor = models.ManyToManyField(Instructor)
    aboutCourse=models.TextField()
    link=models.CharField(max_length = 400,default='https://us04web.zoom.us/j/79969674890?pwd=zpll6laDg59zwfwUSPbTYPZnIVfACS.1')
    audience=models.ManyToManyField(Audience)
    last_modified = models.DateTimeField(auto_now_add = True)
    img = models.ImageField(upload_to = "static/media/")
    #video=models.ManyToManyField(Video)
    #content=models.ForeignKey(Content, on_delete=models.CASCADE, blank=False, null=True)
    def __str__(self):
        return self.title

class Content(models.Model):
    title=models.CharField(max_length=100)
    course=models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    #videos=models.ManyToManyField(Video)

    def __str__(self):
        return self.title
class Video(models.Model):
    caption=models.CharField(max_length=100)
    slug=models.CharField(max_length=100,default="")
    video=models.FileField(upload_to = "video/%y")
    length=models.IntegerField()
    term=models.CharField(max_length = 20,default='3h 20m')
    content=models.ForeignKey(Content, on_delete=models.CASCADE, blank=False, null=True)
    course=models.ForeignKey(Course, on_delete=models.CASCADE, blank=False, null=True)
    def save(self, *args, **kwargs):
        if self.length >= 60:
            self.term = str(int(self.length/60))+"h "+str(int(self.length%60))+"m"
        else:
            self.term = str(self.length)+"m"
        super(Video, self).save(*args, **kwargs)
    def __str__(self):
        return str(self.caption) + " : "+ str(self.term)

class UserCourse(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=True)
    course=models.ForeignKey(Course, on_delete=models.CASCADE, blank=False, null=True)
    paid=models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    #checkout=models.ForeignKey(Checkout, on_delete=models.CASCADE, blank=False, null=True)
    def __str__(self):
        return self.user.first_name+" - " +self.course.title

templates/instructor/instructors.html
<head>
    <link rel="stylesheet" href="static/css/home_middle.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--ai ta use korle kichu icon shpae change hoye jay.so trying to avoid this.
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  -->
<!--<link
  rel="stylesheet"
  href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
  crossorigin="anonymous"
/>-->
<!--for boostrap icon-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<div class="container my-5">
<div class="container my-5">
    <h4 style="background:#c5c5c5;font-weight:900;color:blueviolet;text-align:center;padding: 5px;">শিক্ষক</h4>
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-4">
    {% for ustad in ustad %}
    <div class="col">
      <div class="card">
        <img class="img rounded-circle mx-auto d-block" src="/static/image/man.jpg" alt="..."  style="width:50%">
        <div class="card-body">
          <h5 class="card-title" style="font-weight:700;color:blueviolet">{{ustad.name}}</h5>
          <p class="card-text">{{ustad.title}}</p>
          <a href="{% url 'ustaz' ustad.name %}" class="btn btn-primary">বিস্তারিত</a>
          
        </div>
      </div>
    </div>
    {% endfor %}
</div>
<div class="container my-5">
    <h4 style="background:#c5c5c5;font-weight:900;color:blueviolet;text-align:center;padding: 5px;">শিক্ষিকা</h4>
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-4">
    {% for ustadi in ustadi %}
    <div class="col">
      <div class="card">
        <img class="img rounded-circle mx-auto d-block" src="/static/image/8.jpeg" alt="..."  style="width:50%">
        <div class="card-body">
          <h5 class="card-title" style="font-weight:700;color:blueviolet">{{ustadi.name}}</h5>
          <p class="card-text"><span>{{ustadi.title}}</span></p>
          <a href="{% url 'ustaz' ustadi.name %}" class="btn btn-primary">বিস্তারিত</a>
          
        </div>
      </div>
    </div>
    {% endfor %}
</div>
</div>

templates/instructor/ustaz.html
<head>
    <link rel="stylesheet" href="static/css/home_middle.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--ai ta use korle kichu icon shpae change hoye jay.so trying to avoid this.
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  -->
<!--<link
  rel="stylesheet"
  href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
  integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
  crossorigin="anonymous"
/>-->
<!--for boostrap icon-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<div class="card mb-3" style="max-width: 840px;margin-left: 140px;">
    <div class="row g-0">
      <div class="col-md-4">
        {% if ustaz.gender == 'man' %}
        <img class="img rounded-circle mx-auto d-block" src="/static/image/man.jpg" alt="..."  style="width:100%">
        {% else %}
        <img class="img rounded-circle mx-auto d-block" src="/static/image/8.jpeg" alt="..."  style="width:100%">
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{ustaz.name}}</h5>
          <p class="card-text">{{ustaz.title}}</p>
          <p class="card-text" style="font-size: 14px;">{{ustaz.instructor_resume}}</p>
          <p class="card-text"><small class="text-muted">Last updated 3 month ago</small></p>
        </div>
      </div>
    </div>
  </div>

<div class="container my-5">
<div class="container my-5">
    <h4 style="font-weight:900;color:blueviolet;text-align:center">{{designation}} কোর্সসমূহ</h4>
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-4">
    {% for course in course %}
    <div class="col">
      <div class="card">
        <img src="{{course.img.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title" style="font-weight:700;color:blueviolet">{{course.title}}</h5>
          <p class="card-text"><span><i class="bi bi-person-fill"></i>  {{course.usercourse_set.all.count}}</span>&emsp;<span><i class="bi bi-clock-history"></i> {{course.duration}}</span></p>
          <!--<p class="card-text">{{course.instructor}}</p>-->
          <a href="{% url 'course_details' course.slug %}" class="btn btn-primary">বিস্তারিত জানুন</a>
          
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

templates/instructor/wrap.html
{% extends 'layout.html' %}
{% block title %}
instructors - {{ustaz.name}}
{% endblock %}
{% block  content %}
{% include 'instructor/ustaz.html' %}

{% endblock  %}

templates/instructor/wrap_instructors.html
{% extends 'layout.html' %}
{% block title %}
instructors
{% endblock %}
{% block  content %}
{% include 'instructor/instructors.html' %}

{% endblock  %}